//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriadProductionOrderCalendar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TKMDEntities : DbContext
    {
        public TKMDEntities()
            : base("name=TKMDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mh_tbl_comp_lines> mh_tbl_comp_lines { get; set; }
        public DbSet<mh_tbl_gannt_chart> mh_tbl_gannt_chart { get; set; }
        public DbSet<mh_tbl_prod_Sched_Original> mh_tbl_prod_Sched_Original { get; set; }
        public DbSet<mh_tbl_qty_totals> mh_tbl_qty_totals { get; set; }
    }
}
