//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriadProductionOrderCalendar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mh_tbl_comp_lines
    {
        public decimal prod_order_number { get; set; }
        public string item_id { get; set; }
        public decimal qty_requested { get; set; }
        public decimal qty_allocated { get; set; }
        public string complete { get; set; }
        public string disposition { get; set; }
        public string printed { get; set; }
        public System.DateTime required_date { get; set; }
        public decimal source_location_id { get; set; }
        public decimal qty_on_pick_tickets { get; set; }
        public decimal qty_confirmed { get; set; }
    }
}
